# Gunakan Node.js versi LTS
FROM node:18-alpine

# Set folder kerja
WORKDIR /app

# Copy package.json dan package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy seluruh kode frontend
COPY . .

# Build aplikasi Next.js untuk production
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Jalankan aplikasi
CMD ["npm", "start"]