-- Copy and paste this into the Supabase SQL Editor

CREATE TABLE IF NOT EXISTS storage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    temperature FLOAT NOT NULL,
    humidity FLOAT NOT NULL,
    device_id TEXT NOT NULL
);

-- Optional: Enable Row Level Security (RLS) if needed, 
-- but for this Hackathon demo it's fine to leave it open or public for read/write
-- ALTER TABLE storage_logs ENABLE ROW LEVEL SECURITY;
